# Generated by Django 5.1.5 on 2025-01-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='mes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='mes',
            field=models.IntegerField(default=1),
        ),
    ]
