# Generated by Django 5.1.5 on 2025-01-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_gasto_mes_ingreso_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
