# Generated by Django 5.1.5 on 2025-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_gasto_fecha_alter_gasto_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('comprado', models.BooleanField(default=False)),
            ],
        ),
    ]
