# Generated by Django 5.1.5 on 2025-01-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_listacompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='mes',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
